version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rentiva-postgres
    environment:
      POSTGRES_DB: rentiva
      POSTGRES_USER: rentiva_user
      POSTGRES_PASSWORD: rentiva_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rentiva-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rentiva-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/rentiva
      POSTGRES_USER: rentiva_user
      POSTGRES_PASSWORD: rentiva_password
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - rentiva-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rentiva-frontend
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rentiva-network

  # Admin Panel Service
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: rentiva-admin
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - rentiva-network

volumes:
  postgres_data:

networks:
  rentiva-network:
    driver: bridge
