services:
  # Backend Service
  - type: web
    name: rentiva-backend
    env: java
    plan: free
    buildCommand: |
      cd backend
      ./mvnw clean package -DskipTests
    startCommand: |
      cd backend
      java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: https://rentiva-frontend.onrender.com,https://rentiva-admin.onrender.com
      - key: DATABASE_URL
        value: postgresql://rentiva_database_user:MOTsewR9SbhIDRJAsd4y9RZA4mqaac3N@dpg-d260hbbe5dus73cu2g90-a.oregon-postgres.render.com/rentiva_database
      # Additional database environment variables
      - key: RENDER_DATABASE_HOST
        value: dpg-d260hbbe5dus73cu2g90-a.oregon-postgres.render.com
      - key: RENDER_DATABASE_PORT
        value: 5432
      - key: RENDER_DATABASE_NAME
        value: rentiva_database
      - key: RENDER_DATABASE_USER
        value: rentiva_database_user
      - key: RENDER_DATABASE_PASSWORD
        value: MOTsewR9SbhIDRJAsd4y9RZA4mqaac3N
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: rentiva-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://rentiva-backend.onrender.com
      - key: NODE_ENV
        value: production

  # Admin Panel Static Site
  - type: web
    name: rentiva-admin
    env: static
    plan: free
    buildCommand: |
      cd admin
      npm ci
      npm run build
    staticPublishPath: admin/dist
    envVars:
      - key: VITE_API_URL
        value: https://rentiva-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"

databases:
  - name: rentiva-db
    databaseName: rentiva
    user: rentiva_user
    plan: free
