services:
  # Backend Service
  - type: web
    name: rentiva-backend
    env: java
    plan: free
    buildCommand: |
      cd backend
      ./mvnw clean package -DskipTests
    startCommand: |
      cd backend
      java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: https://rentiva-frontend.onrender.com,https://rentiva-admin.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: rentiva-db
          property: connectionString
    healthCheckPath: /actuator/health

  # Frontend Service
  - type: web
    name: rentiva-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        value: https://rentiva-backend.onrender.com
      - key: NODE_ENV
        value: production

  # Admin Panel Service
  - type: web
    name: rentiva-admin
    env: node
    plan: free
    buildCommand: |
      cd admin
      npm install
      npm run build
    startCommand: |
      cd admin
      npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        value: https://rentiva-backend.onrender.com
      - key: NODE_ENV
        value: production

databases:
  - name: rentiva-db
    databaseName: rentiva
    user: rentiva_user
    plan: free
