name: Keep Render Server Alive

on:
  schedule:
    - cron: '*/5 * * * *' # co 5 minut
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Render backend
        run: curl -s https://rentiva-admin-zmr9.onrender.com > /dev/null
